### ISSUE TITLE
Wallpaper displayed as just blue in app drawer, multitasking and other places on One UI 6.0.

### ISSUE THREAD

**Issue by VonSparq** [markusfisch/WaveLinesWallpaper#14]
Hi, I recently updated my phone to Android 14 with Samsung's One UI 6.0 skin, and I've encountered an issue with the wallpaper not being properly displayed in some places.
It works fine on the lock and home screens, but displays as just light blue in the multitasking view, the app drawer and a few other places.
![bug](https://github.com/markusfisch/WaveLinesWallpaper/assets/78357458/199f7b16-5907-4ff8-97c9-7e18f719e486)

I really like this wallpaper, it's been my favorite for many years and I would like to thank you for making it because it really looks awesome and has a great many customization options. I would really love to continue using it for many more years and hope you manage to resolve this issue!

**Comment by markusfisch** [comment]
Thank you for filing an issue about this! I wasn't aware of that bug. I will try to find a solution…

**Comment by markusfisch** [comment]
Fixed in https://github.com/markusfisch/WaveLinesWallpaper/commit/b83c23bdaeb090c0dfec9d0327fe0cba8a422e1b

The reason for the blue background was that Samsung's One UI is simply using the (heavily blurred) thumbnail of the live wallpaper as a static background for the app drawer (and task switcher).

Version [1.13.4](https://github.com/markusfisch/WaveLinesWallpaper/releases/tag/1.13.4) is on its way through Google Play and should become available soon.
